services:
  - type: web
    name: student-planner-api
    env: node
    region: oregon
    plan: free
    rootDir: student-planner/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://student-planner-client.onrender.com
      - key: FRONTEND_URL
        value: https://student-planner-client.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://student-planner-api.onrender.com/api/auth/google/callback
      - key: DATABASE_URL
        value: postgresql://postgres.ncuanobkrkufelsrnqxc:Oladapo%40123@aws-1-eu-central-2.pooler.supabase.com:6543/postgres

  - type: web
    name: student-planner-client
    env: static
    region: oregon
    plan: free
    rootDir: student-planner/client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://student-planner-api.onrender.com

